version: '3.1'
services:
  db:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - "./initdb.d:/docker-entrypoint-initdb.d"
      - "mysql-data:/var/lib/mysql"
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql-data: