version: '3.1'
services:
  db:
    image: mysql:5.7.23
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  # TODO: 初回起動が失敗してします。DBの初期化の関係?
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  mysql-data: